#!/usr/bin/env bash

killall sxhkd

sxhkd &

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config normal_border_color  "#4C566A"
bspc config focused_border_color "#BF616A"
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle			 true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


bspc rule -a *:FuzzyWindow state=floating center=on sticky=on

# $HOME/.config/polybar/launch.sh
