#!/usr/bin/env bash

forgit_log=glog
forgit_checkout_file=gr
forgit_checkout_branch=gbb

FORGIT_FZF_DEFAULT_OPTS="
--bind='alt-b:preview-page-up,ctrl-u:preview-page-up'
--bind='alt-f:preview-page-down,ctrl-d:preview-page-down'
"

FORGIT_DIFF_FZF_OPTS="
--bind='ctrl-o:execute(nvim {})'
"
